Repository wecode-bootcamp-korea/43-1st-soleMates-frontend, pull requests merged in 2023-03, with the labels that each got.

#3 [43기 김수미] add : 푸터 기능구현
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
Labels: 완료

#9 [43기 김수미] add : 장바구니 일부 마크업인데 체크박스 부분 공통컴포넌트로 만들어서 리뷰 요청따로드립니다
  public/images/Common/ico_shop.svg
  src/Components/ItemChoice/ItemChoice.js
  src/Components/ItemChoice/ItemChoice.scss
  src/style/common.scss
Labels: 완료

#5 [43기 김수미] add : 헤더 구현 및 컴포넌트화 완료
  public/images/Header/img_logo.png
  public/images/Main/@bnr2_1440x900.jpg
  public/images/Main/@bnr3_1440x900.jpg
  public/images/Main/@bnr_1440x900.jpeg
  public/images/Main/@bnr_1440x900.jpg
  public/images/Main/@bnr_720x900.gif
  public/images/Main/@thumb_279x349.jpg
  public/images/Nav/logo.png
  src/Components/Header/Banner/Banner.js
  src/Components/Header/Banner/Banner.scss
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/Header/LinkUtil/LinkUtil.js
  src/Components/Header/LinkUtil/LinkUtil.scss
  src/Components/Header/ListMenu/CateList.js
  src/Components/Header/ListMenu/ListMenu.js
  src/Components/Header/ListMenu/ListMenu.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Router.js
  src/style/common.scss
Labels: 완료

#7 [43기홍태훈] add : Feature/detail 페이지 마크업 및 기능 일부 구현
  public/images/ProductDetail/product1.jpg
  public/images/ProductDetail/productlist.png
  public/images/ProductDetail/red.png
  public/images/ProductDetail/yellowboots.jpg
  src/Router.js
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
  src/pages/Detail/ModalToCart.js
  src/pages/Detail/ModalToCart.scss
Labels: 멘토 리뷰 요청

#8 [43기 김수미] add : 장바구니 일부 마크업 + 기능구현 완료
  public/data/cartProduct.json
  public/images/Product/@thumb_266x334.png
  src/Components/ItemChoice/ItemChoice.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/EmptyCart/EmptyCart.js
  src/pages/Cart/EmptyCart/EmptyCart.scss
  src/pages/Cart/GroupCart/GroupCart.js
  src/pages/Cart/GroupCart/GroupCart.scss
  src/pages/Cart/Item/Item.js
  src/pages/Cart/Item/Item.scss
Labels: 완료

#14 [43기 김수미] update : 백앤드와 통신후 수정
  src/pages/Cart/Cart.js
  src/pages/Cart/Item/Item.js
Labels: 리뷰 진행 중

#13 [43기 김수미] update : 메인 링크 연결
  public/images/Main/@bnr2_1440x900.jpg
  public/images/Main/@bnr2_1440x900.png
  public/images/Main/@bnr3_1440x900.jpg
  public/images/Main/@bnr3_1440x900.png
  public/images/Main/@bnr4_1440x900.jpg
  public/images/Main/@bnr_1440x900.jpg
  public/images/Main/@bnr_1440x900.png
  public/images/Main/@bnr_720x900.png
  public/images/Main/@thumb2_500x750.jpg
  public/images/Main/@thumb_500x750.jpg
  public/images/Main/@thumb_506x524.png
  public/images/Main/@thumb_620x371.jpg
  src/Router.js
  src/pages/Main/ListProducts/ListProducts.scss
  src/pages/Main/Main.js
  src/pages/Main/MainSlide/MainSlide.js
Labels: 멘토 리뷰 요청

#11 [43기 이기태] add :상품리스트 기능구현 완료
  public/data/productList.json
  public/images/ProductList/productlist.png
  public/index.html
  src/pages/ProductList/Filter/Filter.js
  src/pages/ProductList/FilterSizeButton/FilterSizeButton.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/ProductListImage/BTN_COLOR.js
  src/pages/ProductList/ProductListImage/ProductListImage.js
  src/pages/ProductList/ProductListImage/ProductListImage.scss
  src/pages/ProductList/SizeButton/SizeButton.js
  src/pages/ProductList/WrapInfo/WrapInfo.js
Labels: 멘토 리뷰 요청
